# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#    This file is part of FRC Team 3341 Aimer.
#
#    FRC Team 3341 Aimer is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    FRC Team 3341 Aimer is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with FRC Team 3341 Aimer.  If not, see <http://www.gnu.org/licenses/>.




pkgdatadir = $(datadir)/frc-team-3341-aimer
pkgincludedir = $(includedir)/frc-team-3341-aimer
pkglibdir = $(libdir)/frc-team-3341-aimer
pkglibexecdir = $(libexecdir)/frc-team-3341-aimer
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = frc-team-3341-aimer$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(dist_noinst_DATA) \
	$(dist_noinst_SCRIPTS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/src/config.h.in AUTHORS COPYING ChangeLog \
	INSTALL NEWS TODO compile depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_frc_team_3341_aimer_OBJECTS =  \
	src/frc_team_3341_aimer-Constants.$(OBJEXT) \
	src/frc_team_3341_aimer-CRIOLink.$(OBJEXT) \
	src/frc_team_3341_aimer-HSVImage.$(OBJEXT) \
	src/frc_team_3341_aimer-main.$(OBJEXT) \
	src/frc_team_3341_aimer-Rectangle.$(OBJEXT) \
	src/frc_team_3341_aimer-RectangleDetector.$(OBJEXT) \
	src/frc_team_3341_aimer-VideoDevice.$(OBJEXT)
frc_team_3341_aimer_OBJECTS = $(am_frc_team_3341_aimer_OBJECTS)
frc_team_3341_aimer_LDADD = $(LDADD)
frc_team_3341_aimer_LINK = $(CXXLD) $(frc_team_3341_aimer_CXXFLAGS) \
	$(CXXFLAGS) $(frc_team_3341_aimer_LDFLAGS) $(LDFLAGS) -o $@
SCRIPTS = $(dist_noinst_SCRIPTS)
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(frc_team_3341_aimer_SOURCES)
DIST_SOURCES = $(frc_team_3341_aimer_SOURCES)
DATA = $(dist_noinst_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run tar
AUTOCONF = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run autoconf
AUTOHEADER = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run autoheader
AUTOMAKE = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -march=native -O2 -pipe
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -march=native -O2 -pipe
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = frc-team-3341-aimer
PACKAGE_BUGREPORT = software@wvrobotics.com
PACKAGE_NAME = FRC Team 3341 Aimer
PACKAGE_STRING = FRC Team 3341 Aimer 2012.3
PACKAGE_TARNAME = frc-team-3341-aimer
PACKAGE_URL = http://wvrobotics.com/
PACKAGE_VERSION = 2012.3
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 2012.3
abs_builddir = /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer
abs_srcdir = /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer
abs_top_builddir = /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer
abs_top_srcdir = /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/tushar/Documents/School/9th-grade/robotics/frc/programming/image-processing/opencv/frc-team-3341-aimer/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
frc_team_3341_aimer_LDFLAGS = `pkg-config --cflags --libs opencv`
frc_team_3341_aimer_CXXFLAGS = -Wall -std=gnu++0x
frc_team_3341_aimer_SOURCES = src/Constants.cpp src/Constants.hpp src/CRIOLink.cpp src/CRIOLink.hpp src/HSVImage.cpp src/HSVImage.hpp src/main.cpp src/Rectangle.cpp src/Rectangle.hpp src/RectangleDetector.cpp src/RectangleDetector.hpp src/VideoDevice.cpp src/VideoDevice.hpp
dist_noinst_SCRIPTS = autogen.sh
dist_noinst_DATA = images/
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

src/config.h: src/stamp-h1
	@if test ! -f $@; then \
	  rm -f src/stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) src/stamp-h1; \
	else :; fi

src/stamp-h1: $(top_srcdir)/src/config.h.in $(top_builddir)/config.status
	@rm -f src/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/config.h
$(top_srcdir)/src/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f src/stamp-h1
	touch $@

distclean-hdr:
	-rm -f src/config.h src/stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-Constants.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-CRIOLink.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-HSVImage.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-Rectangle.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-RectangleDetector.$(OBJEXT):  \
	src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/frc_team_3341_aimer-VideoDevice.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
frc-team-3341-aimer$(EXEEXT): $(frc_team_3341_aimer_OBJECTS) $(frc_team_3341_aimer_DEPENDENCIES) 
	@rm -f frc-team-3341-aimer$(EXEEXT)
	$(frc_team_3341_aimer_LINK) $(frc_team_3341_aimer_OBJECTS) $(frc_team_3341_aimer_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-CRIOLink.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-Constants.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-HSVImage.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-Rectangle.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-RectangleDetector.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-VideoDevice.$(OBJEXT)
	-rm -f src/frc_team_3341_aimer-main.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Po
include src/$(DEPDIR)/frc_team_3341_aimer-Constants.Po
include src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Po
include src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Po
include src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Po
include src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Po
include src/$(DEPDIR)/frc_team_3341_aimer-main.Po

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/frc_team_3341_aimer-Constants.o: src/Constants.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-Constants.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-Constants.Tpo -c -o src/frc_team_3341_aimer-Constants.o `test -f 'src/Constants.cpp' || echo '$(srcdir)/'`src/Constants.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-Constants.Tpo src/$(DEPDIR)/frc_team_3341_aimer-Constants.Po
#	source='src/Constants.cpp' object='src/frc_team_3341_aimer-Constants.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-Constants.o `test -f 'src/Constants.cpp' || echo '$(srcdir)/'`src/Constants.cpp

src/frc_team_3341_aimer-Constants.obj: src/Constants.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-Constants.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-Constants.Tpo -c -o src/frc_team_3341_aimer-Constants.obj `if test -f 'src/Constants.cpp'; then $(CYGPATH_W) 'src/Constants.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Constants.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-Constants.Tpo src/$(DEPDIR)/frc_team_3341_aimer-Constants.Po
#	source='src/Constants.cpp' object='src/frc_team_3341_aimer-Constants.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-Constants.obj `if test -f 'src/Constants.cpp'; then $(CYGPATH_W) 'src/Constants.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Constants.cpp'; fi`

src/frc_team_3341_aimer-CRIOLink.o: src/CRIOLink.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-CRIOLink.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Tpo -c -o src/frc_team_3341_aimer-CRIOLink.o `test -f 'src/CRIOLink.cpp' || echo '$(srcdir)/'`src/CRIOLink.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Tpo src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Po
#	source='src/CRIOLink.cpp' object='src/frc_team_3341_aimer-CRIOLink.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-CRIOLink.o `test -f 'src/CRIOLink.cpp' || echo '$(srcdir)/'`src/CRIOLink.cpp

src/frc_team_3341_aimer-CRIOLink.obj: src/CRIOLink.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-CRIOLink.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Tpo -c -o src/frc_team_3341_aimer-CRIOLink.obj `if test -f 'src/CRIOLink.cpp'; then $(CYGPATH_W) 'src/CRIOLink.cpp'; else $(CYGPATH_W) '$(srcdir)/src/CRIOLink.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Tpo src/$(DEPDIR)/frc_team_3341_aimer-CRIOLink.Po
#	source='src/CRIOLink.cpp' object='src/frc_team_3341_aimer-CRIOLink.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-CRIOLink.obj `if test -f 'src/CRIOLink.cpp'; then $(CYGPATH_W) 'src/CRIOLink.cpp'; else $(CYGPATH_W) '$(srcdir)/src/CRIOLink.cpp'; fi`

src/frc_team_3341_aimer-HSVImage.o: src/HSVImage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-HSVImage.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Tpo -c -o src/frc_team_3341_aimer-HSVImage.o `test -f 'src/HSVImage.cpp' || echo '$(srcdir)/'`src/HSVImage.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Tpo src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Po
#	source='src/HSVImage.cpp' object='src/frc_team_3341_aimer-HSVImage.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-HSVImage.o `test -f 'src/HSVImage.cpp' || echo '$(srcdir)/'`src/HSVImage.cpp

src/frc_team_3341_aimer-HSVImage.obj: src/HSVImage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-HSVImage.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Tpo -c -o src/frc_team_3341_aimer-HSVImage.obj `if test -f 'src/HSVImage.cpp'; then $(CYGPATH_W) 'src/HSVImage.cpp'; else $(CYGPATH_W) '$(srcdir)/src/HSVImage.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Tpo src/$(DEPDIR)/frc_team_3341_aimer-HSVImage.Po
#	source='src/HSVImage.cpp' object='src/frc_team_3341_aimer-HSVImage.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-HSVImage.obj `if test -f 'src/HSVImage.cpp'; then $(CYGPATH_W) 'src/HSVImage.cpp'; else $(CYGPATH_W) '$(srcdir)/src/HSVImage.cpp'; fi`

src/frc_team_3341_aimer-main.o: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-main.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-main.Tpo -c -o src/frc_team_3341_aimer-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-main.Tpo src/$(DEPDIR)/frc_team_3341_aimer-main.Po
#	source='src/main.cpp' object='src/frc_team_3341_aimer-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

src/frc_team_3341_aimer-main.obj: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-main.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-main.Tpo -c -o src/frc_team_3341_aimer-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-main.Tpo src/$(DEPDIR)/frc_team_3341_aimer-main.Po
#	source='src/main.cpp' object='src/frc_team_3341_aimer-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

src/frc_team_3341_aimer-Rectangle.o: src/Rectangle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-Rectangle.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Tpo -c -o src/frc_team_3341_aimer-Rectangle.o `test -f 'src/Rectangle.cpp' || echo '$(srcdir)/'`src/Rectangle.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Tpo src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Po
#	source='src/Rectangle.cpp' object='src/frc_team_3341_aimer-Rectangle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-Rectangle.o `test -f 'src/Rectangle.cpp' || echo '$(srcdir)/'`src/Rectangle.cpp

src/frc_team_3341_aimer-Rectangle.obj: src/Rectangle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-Rectangle.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Tpo -c -o src/frc_team_3341_aimer-Rectangle.obj `if test -f 'src/Rectangle.cpp'; then $(CYGPATH_W) 'src/Rectangle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Rectangle.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Tpo src/$(DEPDIR)/frc_team_3341_aimer-Rectangle.Po
#	source='src/Rectangle.cpp' object='src/frc_team_3341_aimer-Rectangle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-Rectangle.obj `if test -f 'src/Rectangle.cpp'; then $(CYGPATH_W) 'src/Rectangle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Rectangle.cpp'; fi`

src/frc_team_3341_aimer-RectangleDetector.o: src/RectangleDetector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-RectangleDetector.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Tpo -c -o src/frc_team_3341_aimer-RectangleDetector.o `test -f 'src/RectangleDetector.cpp' || echo '$(srcdir)/'`src/RectangleDetector.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Tpo src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Po
#	source='src/RectangleDetector.cpp' object='src/frc_team_3341_aimer-RectangleDetector.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-RectangleDetector.o `test -f 'src/RectangleDetector.cpp' || echo '$(srcdir)/'`src/RectangleDetector.cpp

src/frc_team_3341_aimer-RectangleDetector.obj: src/RectangleDetector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-RectangleDetector.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Tpo -c -o src/frc_team_3341_aimer-RectangleDetector.obj `if test -f 'src/RectangleDetector.cpp'; then $(CYGPATH_W) 'src/RectangleDetector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RectangleDetector.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Tpo src/$(DEPDIR)/frc_team_3341_aimer-RectangleDetector.Po
#	source='src/RectangleDetector.cpp' object='src/frc_team_3341_aimer-RectangleDetector.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-RectangleDetector.obj `if test -f 'src/RectangleDetector.cpp'; then $(CYGPATH_W) 'src/RectangleDetector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RectangleDetector.cpp'; fi`

src/frc_team_3341_aimer-VideoDevice.o: src/VideoDevice.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-VideoDevice.o -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Tpo -c -o src/frc_team_3341_aimer-VideoDevice.o `test -f 'src/VideoDevice.cpp' || echo '$(srcdir)/'`src/VideoDevice.cpp
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Tpo src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Po
#	source='src/VideoDevice.cpp' object='src/frc_team_3341_aimer-VideoDevice.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-VideoDevice.o `test -f 'src/VideoDevice.cpp' || echo '$(srcdir)/'`src/VideoDevice.cpp

src/frc_team_3341_aimer-VideoDevice.obj: src/VideoDevice.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -MT src/frc_team_3341_aimer-VideoDevice.obj -MD -MP -MF src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Tpo -c -o src/frc_team_3341_aimer-VideoDevice.obj `if test -f 'src/VideoDevice.cpp'; then $(CYGPATH_W) 'src/VideoDevice.cpp'; else $(CYGPATH_W) '$(srcdir)/src/VideoDevice.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Tpo src/$(DEPDIR)/frc_team_3341_aimer-VideoDevice.Po
#	source='src/VideoDevice.cpp' object='src/frc_team_3341_aimer-VideoDevice.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(frc_team_3341_aimer_CXXFLAGS) $(CXXFLAGS) -c -o src/frc_team_3341_aimer-VideoDevice.obj `if test -f 'src/VideoDevice.cpp'; then $(CYGPATH_W) 'src/VideoDevice.cpp'; else $(CYGPATH_W) '$(srcdir)/src/VideoDevice.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
